version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_testoauth2
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: testoauth2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
